Azienda2/core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managementApp.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Azienda2/core/managementApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

app_name="managementApp"

urlpatterns = [
    path('', views.lista_dipendenti, name='lista_dipendenti'),
    path('azienda/<slug:azienda_slug>', views.dipendente_azienda, name='dipendente_azienda'),
    path('sede/<slug:sede_slug>', views.dipendente_sede, name='dipendente_sede'),
    path('dipendente/<str:dipendente_nome>', views.dipendente_detail, name='dipendente_detail'),
    #CRUD
    path('crea_dipedente/', views.create_dipendente, name='create_dipendente'),
    path('update_dipendente/<str:nome>', views.update_dipendente, name='update_dipendente'),
    path('delete_dipendente/<str:pk>', views.delete_dipendente, name='delete_dipendente'),
    #Registration
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html',  form_class=AuthenticationForm, next_page='/'), name='login'),

    #path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),


  
   
]

Azienda2/core/managementApp/models.py
from django.db import models
from django.urls import reverse


class Sede1(models.Model):
    indirizzo = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True)

    def get_absolute_url(self):
        return reverse('managementApp:dipendente_sede', args=[self.slug])

    def __str__(self):
        return self.indirizzo

class Azienda1(models.Model):
    nomeAzienda = models.CharField(max_length=200)
    immagine = models.ImageField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    def get_absolute_url(self):
        return reverse('managementApp:dipendente_azienda', args=[self.slug])

    def __str__(self):
        return self.nomeAzienda

class Dipendente1(models.Model):
    nome = models.CharField(max_length=200)
    cognome = models.CharField(max_length=200)
    immagine = models.ImageField(blank=True)
    sede = models.ForeignKey(Sede1, on_delete=models.CASCADE)
    azienda = models.ForeignKey(Azienda1, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('managementApp:dipendente_detail', args=[self.nome])
    
    

    def __str__(self):
        return self.nome

class Ordine(models.Model):
    dipendente = models.ForeignKey(Dipendente1, on_delete=models.CASCADE)
    prezzo = models.IntegerField()










Azienda2/core/managementApp/forms.py
from django.forms import ModelForm
from .models import Dipendente1


class DipendenteForm(ModelForm):
    class Meta:
        model = Dipendente1
        fields = '__all__'

Azienda2/core/managementApp/views.py
from django.shortcuts import render, redirect
from .models import Azienda1, Sede1, Dipendente1
from django.shortcuts import get_object_or_404
from .forms import DipendenteForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def lista_dipendenti(request):
    aziende = Azienda1.objects.all()
    dipendenti = Dipendente1.objects.all()
    sedi = Sede1.objects.all()
    return render(request, 'lista_dipendenti.html', {'aziende':aziende, 'dipendenti':dipendenti, 'sedi':sedi})

def dipendente_azienda(request, azienda_slug):
    azienda = get_object_or_404(Azienda1, slug=azienda_slug)
    aziende = Azienda1.objects.all()
    dipendenti = Dipendente1.objects.filter(azienda=azienda)
    return render(request, 'dipendente_azienda.html', {'azienda' : azienda, 'dipendenti' : dipendenti, 'aziende' : aziende})


def dipendente_sede(request, sede_slug):
    sede = get_object_or_404(Sede1, slug=sede_slug)
    sedi = Sede1.objects.all()
    dipendenti = Dipendente1.objects.filter(sede=sede)
    return render(request, 'dipendente_sede.html', {'sede' : sede, 'sedi' : sedi, 'dipendenti' : dipendenti} )



def dipendente_detail(request, dipendente_nome):
    dipendente = get_object_or_404(Dipendente1, nome=dipendente_nome)
    return render(request, 'dipendente_detail.html', {'dipendente' : dipendente})


def create_dipendente(request):
    form = DipendenteForm()
    
    if request.method == 'POST':
        form = DipendenteForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
            

    context={'form':form}
    return render(request, 'crud/form_dipendente.html', context)

def update_dipendente(request, nome):

    dipendente = Dipendente1.objects.get(nome=nome) 
    form = DipendenteForm(instance=dipendente)

    if request.method == 'POST':
        form = DipendenteForm(request.POST, request.FILES, instance=dipendente)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form':form}
    return render(request, 'crud/form_dipendente.html', context)

def delete_dipendente(request, pk):
    dipendente = Dipendente1.objects.get(id=pk)
    if request.method == 'POST':
        dipendente.delete() #cancello il dipendente che ho preso con l'id

   
    context = {'dipendente' : dipendente}
    return render(request, 'crud/delete_dipendente.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
            form.save()
            return redirect('managementApp:login')
    
    else:
        form = UserCreationForm()

   
    context = { 'form' : form}
    return render(request, 'registration/register.html',context)

def login(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data= request.POST)
        if form.is_valid():
            return redirect('managementApp:lista_dipendenti')
    
    else: 
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form' : form})
    

Azienda2/core/templates/common/base.html
<html>

<head>


</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link mx-5 " aria-current="page" href="{% url 'managementApp:lista_dipendenti' %}">Home</a>
                        <a class="nav-link " aria-current="page" href="{% url 'managementApp:create_dipendente' %}">aggiungi dipendente</a>
                        <a class="nav-link " aria-current="page" href="{% url 'managementApp:register' %}">registrati</a>
                        
                        {% if user.is_authenticated %}
                        <a class="nav-link " aria-current="page" href="{% url 'managementApp:logout' %}">logout</a>
                        {% else %}
                        <a class="nav-link " aria-current="page" href="{% url 'managementApp:login' %}">login</a>
                        {% endif %}








                    </div>
                </div>

            </div>
        </nav>



    </div>

</body>

</html>

Azienda2/core/templates/common/footer.html
<html>

<head>


</head>

<body>
    <div class="container">


        {% block content %} {% endblock %}

        <div class="container ">
            <footer class="py-5 bg-dark relative-bottom ">

                <p class="m-0 text-center text-white">Dashboard dipendenti</p>

            </footer>
        </div>
    </div>

</body>

</html>

Azienda2/core/templates/crud/delete_dipendente.html
<html>

<head>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>Crea_dipendenti</title>
</head>

<body>

    {% include 'common/base.html'%} {% block content %}
    <div class="container"></div>

    <br><br><br><br><br><br>
    <div class="row m-5">
        <div class="col-md-6">
            <div class="card card-body">

                <p>sei sicuro di voler cancellare {{ dipendente.nome }}</p>

                <form action="{% url 'managementApp:delete_dipendente' dipendente.id %}" enctype="multipart/form-data" method="POST">
                    {%csrf_token%}
                    <a class="btn btn-warning" href="{% url 'managementApp:lista_dipendenti' %}">Cancel</a>


                    <input class="btn btn-danger" type="submit" name="Confirm">

                </form>

            </div>
        </div>
    </div>

    

    </div>


    {% endblock %} {% include 'common/footer.html'%}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

Azienda2/core/templates/crud/form_dipendente.html
<html>

<head>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>Crea_dipendenti</title>
</head>

<body>

    {% include 'common/base.html'%} {% block content %}

    <br>
    <br>
    <br>
    <h1>aggiungi dipendente</h1>

    {% if form.is_multipart %}
    <form id="form" method="post" enctype="multipart/form-data">
        {% else %}
        <form method="'post"></form>
        {% endif %} {% csrf_token %} {{form.as_p}}

        <input type="submit" name="submit">

    </form>

    {% endblock %} {% include 'common/footer.html'%}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

Azienda2/core/templates/dipendente_azienda.html
<html>

<head>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>Lista_dipendenti</title>
</head>

<body>
    {% include 'common/base.html'%}

    <div class="container m-5">

        <div class="row ">
            <div class="card-fluid text-center" style="width: 18rem">
                <img src="{{azienda.immagine.url }}" class="card-img" alt="..." />
            </div>

        </div>

        <div class="row">
            <div class="dropdown my-5 mx-5">
                <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Aziende
        </button>
                <ul class="dropdown-menu">
                    {% for azienda in aziende %}
                    <li><a class="dropdown-item" href="{{ azienda.get_absolute_url }}">{{ azienda.nomeAzienda }}</a></li>
                    {% endfor %}
                    <li><a class="dropdown-item" href="{% url 'managementApp:lista_dipendenti' %}">All</a></li>


                </ul>



                </ul>
            </div>
        </div>
    </div>

    <div class="container my-5">
        <div class="row">

            <div class="row">
                {%for dipendente in dipendenti %}
                <div class="col-sm">
                    <div class="card-fluid text-center" style="width: 18rem">
                        <img src="{{dipendente.immagine.url }}" class="card-img" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">{{dipendente.nome}} {{dipendente.cognome}}</h5>


                            <div class="mx-2 my-2">
                                <a href="" class="btn btn-dark">view </a>
                            </div>


                            <!--  <a href='{{gfx.descrizione}}' class="btn btn-dark">SWoSH</a> -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
    </div>
    {% include 'common/footer.html'%}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

Azienda2/core/templates/dipendente_detail.html
<html>

<head>
    <link rel="stylesheet" href="static/css/home.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

    <style></style>

    <title>detail</title>
</head>

<body>
    {% include 'common/base.html'%}
    <div class="container py-5">
        <main class="pt-5 py-5">
            <div class="row">
                <div class="col-md-5 mt-5 col-lg-5 order-md-first py-5">
                    <img class="img-fluid mx-auto d-block" width="400px" src="{{dipendente.immagine.url}}" alt="Responsive image">
                </div>
                <div class="col-md-7 col-lg  py-5 mt-5">
                    <h1>{{dipendente.nome}} {{dipendente.cognome}}</h1>
                    <br>
                    <h5>{{dipendente.sede}}</h5>
                    <h5>{{dipendente.azienda}}</h5>
                    <a class="btn btn-dark" href="{% url 'managementApp:update_dipendente' dipendente.nome %}">Update</a>
                    <a class="btn btn-dark" href="{% url 'managementApp:delete_dipendente' dipendente.id %}">Delete</a>
                    {% if user.is_authenticated %} 
                    <a class="btn btn-dark" href="{% url 'managementApp:delete_dipendente' dipendente.id %}">Ordina consulenza</a>
                    {% endif %}

                </div>
            </div>


        </main>
    </div>
    {% include 'common/footer.html'%}
</body>



</html>

Azienda2/core/templates/dipendente_sede.html
<html>

<head>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>sedi</title>
</head>

<body>
    {% include 'common/base.html'%}
    <h1 class="title m-5">{{ sede.indirizzo}}</h1>

    <div class="row">
        <div class="dropdown my-5 mx-5">




            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Sedi
        </button>
            <ul class="dropdown-menu">
                {% for sede in sedi %}
                <li><a class="dropdown-item" href="{{ sede.get_absolute_url }}">{{ sede.indirizzo }}</a></li>
                {% endfor %}
                <li><a class="dropdown-item" href="{% url 'managementApp:lista_dipendenti' %}">All</a></li>


            </ul>
        </div>
    </div>


    </ul>
    </div>

    <div class="container my-5">
        <div class="row">

            <div class="row">
                {%for dipendente in dipendenti %}
                <div class="col-sm">
                    <div class="card-fluid text-center" style="width: 18rem">
                        <img src="{{dipendente.immagine.url }}" class="card-img" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">{{dipendente.nome}} {{dipendente.cognome}}</h5>


                            <div class="mx-2 my-2">
                                <a href="" class="btn btn-dark">view </a>
                            </div>


                            <!--  <a href='{{gfx.descrizione}}' class="btn btn-dark">SWoSH</a> -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <br>
    <br>
    <br>
    <br> {% include 'common/footer.html'%}
</body>


</html>

Azienda2/core/templates/lista_dipendenti.html
<html>

<head>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <title>Lista_dipendenti</title>
</head>

<body>

    {% include 'common/base.html'%} {% block content %}

    <h1 class="title my-5">Lista dipendenti</h1>
    


    {% if user.is_authenticated %} 
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
    {% else %}
        <p>Welcome, new user. Please log in.</p>
    {% endif %}
        


    <div class="row">
        <div class="dropdown my-5 mx-5">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Aziende
        </button>
            <ul class="dropdown-menu">
                {% for azienda in aziende %}
                <li><a class="dropdown-item" href="{{ azienda.get_absolute_url }}">{{ azienda.nomeAzienda }}</a></li>
                {% endfor %}
                <li><a class="dropdown-item" href="{% url 'managementApp:lista_dipendenti' %}">All</a></li>


            </ul>



            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Sedi
        </button>
            <ul class="dropdown-menu">
                {% for sede in sedi %}
                <li><a class="dropdown-item" href="{{ sede.get_absolute_url }}">{{ sede.indirizzo }}</a></li>
                {% endfor %}
                <li><a class="dropdown-item" href="{% url 'managementApp:lista_dipendenti' %}">All</a></li>




            </ul>
        </div>

    </div>

    <div class="container my-5">
        <div class="row">

            <div class="row">
                {%for dipendente in dipendenti %}
                <div class="col-sm">
                    <div class="card-fluid text-center" style="width: 18rem">
                        <img src="{{dipendente.immagine.url }}" class="card-img" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">{{dipendente.nome}} {{dipendente.cognome}}</h5>




                            <div class="mx-2 my-2">
                                <a href="{{ dipendente.get_absolute_url }}" class="btn btn-dark">view </a>
                            </div>


                            <!--  <a href='{{gfx.descrizione}}' class="btn btn-dark">SWoSH</a> -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
    {% include 'common/footer.html'%}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

{% endblock %}